cbv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.ArtistView.as_view(), name='home'),
    path('create/', views.ArtistCreateView.as_view(), name='create_artist'),
    path('artists/',views.ArtistListView.as_view(), name='artist_list'),
    path('artist/<int:pk>/',views.ArtistDetailView.as_view(), name='artist_detail'),
    path('add-edit/<int:pk>/album/edit/', views.ArtistEditView.as_view(), name='album-edit'),
    path('album/',views.AlbumCreateView.as_view(), name='create_album'),
    path('album-list/',views.AlbumListView.as_view(), name='album_list'),
    path('album-detail/<int:pk>', views.AlbumDetailView.as_view(), name='album_detail')
    


]

core/models.py
from enum import Flag
import re
from django.db import models
from django.urls import reverse

# Create your models here.
class Album(models.Model):
    name = models.CharField(null=False, blank=False, max_length=255)
    created = models.TimeField(auto_now_add=True)

    class Meta:
        ordering = ('name',)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('core:album_detail', kwargs={'pk':self.pk})

      

class Artist(models.Model):
    name = models.CharField(null=False, blank=False, max_length=64)
    track = models.CharField(null=True, blank=True, max_length=255)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, null=True, blank=True, max_length=255, related_name='collection_artist')
    created = models.TimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('core:artist_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    def count(self):
        b = Artist.objects.all()
        for artist in b:
            c = artist.collection_artist.all().count()
        return reverse('core:artist_detail', f'{artist.name}  has {c} album(s)')

    class Meta:
        ordering = ('name',)




class Collection(models.Model):
    slug = models.SlugField(max_length=255)
    track = models.CharField(null=True, blank=True, max_length=255)
    artist = models.ForeignKey(Artist, null=True, blank=True, on_delete=models.CASCADE, related_name='collection_artist')
    album = models.ForeignKey(Album, null=True, blank=True, on_delete=models.CASCADE, related_name='collection_album')
    created = models.TimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)


    def __str__(self):
        return self.track

    

core/forms.py
from django.forms.models import inlineformset_factory
from .models import Artist, Collection, Album

ArtistCollection = inlineformset_factory(Artist, Collection, fields=('track', 'album'), extra=5)

core/views.py
import collections
import imp
from unicodedata import name
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, CreateView, FormView
from django.contrib import messages
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Album, Artist, Collection
from .forms import ArtistCollection

from django.db.models import Q
b = Artist.objects.all()

    


# Create your views here.
class ArtistView(TemplateView):
    model = Artist
    template_name = 'home.html'

class ArtistListView(ListView):
    model = Artist
    template_name = 'artist_list.html'


class ArtistDetailView(DetailView):
    model = Artist
    template_name = 'artist_detail.html'



class ArtistCreateView(CreateView):
    model = Artist
    template_name = 'artist_create.html'
    fields = ['name','album',]

    def form_valid(self, form):

        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Artist Created Successfully'
        )
        return super().form_valid(form)


class ArtistEditView(SingleObjectMixin, FormView):
    model = Artist
    template_name = 'artist_collection.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset= Artist.objects.all())
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset= Artist.objects.all())
        return super().post(request, *args, **kwargs)

    def get_form(self, form_class=None):
        return ArtistCollection(**self.get_form_kwargs(), instance=self.object)

    def get_success_url(self):
        return reverse('core:artist_detail', kwargs={'pk':self.object.pk})
    
    def form_valid(self, form):
        form.save()

        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Successfull'
        )
        return HttpResponseRedirect(self.get_success_url())



class AlbumListView(ListView):
    model = Album
    template_name = 'album_list.html'

class AlbumCreateView(CreateView):
    model= Album
    template_name = 'album_create.html'
    fields = ['name', ]

    def form_valid(self, form):

        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Album Created Successfully'
        )
        return super().form_valid(form)

class AlbumDetailView(DetailView):
    model= Album
    template_name = 'album_detail.html'

core/templates/album_create.html
{% extends 'base.html' %}

{% block content %}

      <form action="" method="post">
        {% for hidden_field in form.hidden_fields %}
          {{ hidden_field.errors }}
          {{ hidden_field }}
        {% endfor %}

        {% csrf_token %}

        {{ form.non_form_errors }}

        {% for field in form %}
          {{ field.errors }}
          {{ field.label_tag }} {{ field }}
          <br><br>
        {% endfor %}

        <p class="pt-2">
            <button type="submit" class="btn btn-primary w-100 mb-2">Create Album</button>
            <a href="{% url 'core:home' %}" role="button" class="btn btn-secondary w-100">Cancel</a>
        </p>
      </form>

{% endblock content %}

core/templates/album_detail.html
{% extends 'base.html' %}

{% block Title %}{{ album.name }}{% endblock %}

{% block content %}
{% if messages %}
{% for message in messages %}
<h4>{{ message }}</h4>
{% endfor %}
{% endif %}

<h3>{{ album.name }} </h3>
    <!-- <div class="d-flex d-flex-inline"><span class="pe-2">Artist name:</span> <h5>{{ artist.name|title }}</h5></div> -->
    <hr>
        {% for collection in album.collection_album.all %}
        <!-- <div class="small">Album: {{ album.name }}</div> -->
        <div class="small">Track: {{ collection.track }}</div>
        <hr>
        {% endfor %}
    <p>
        <a href="{% url 'core:album_list' %}" role="button" class="btn btn-secondary w-100">All Albums</a>
    </p>

{% endblock %}

core/templates/album_list.html
{% extends 'base.html' %}

{% block title %}Artists{% endblock %}

{% block content %}

<h4>All Albums </h4>

{% if album_list %}
<ul class="list-group">
{% for album in album_list %}
<li class="list-group-item">
    <a class="text-reset" href="{{ album.get_absolute_url }}">{{ album.name }}</a>
</li>
{% endfor %}
</ul>
{% else %}
<p>Sorry! There are no artist registered. </p>
{% endif %}
<p class="pt-2">
    <a href="{% url 'core:home' %}" role="button" class="btn btn-secondary w-100">Cancel</a>
  </p>
{% endblock %}

core/templates/artist_collection.html
{% extends 'base.html' %}
{% block title %}{{ artist.name }}{% endblock %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
    {% endfor %}

    <!-- {% for field in form.visible_fields %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
    {% endfor %} -->

    {% csrf_token %}
    {{ form.management_form }}
    {{ form.non_form_errors }}

    <h3>Edit Album</h3>
    {% for album_form in form.forms %}
    <hr>
    <h6>
    {% if album_form.instance.id %}
    <h6>Album Name: {{ album_form.instance.title|title }}</h6>
    {% else %}
    {% if form.forms|length > 1 %}
    Add album
    {% else %}
    Add another album
    {% endif %}
    {% endif %}
    </h6>
    {% for hidden_field in album_form.hidden_fields %}
        {{ hidden_field.errors }}
      {% endfor %}
      <table>
        {{ album_form.as_p }}
      </table>
    {% endfor %}

    <p>
        <button type="submit" value="Update album" class="btn btn-primary w-100 mb-3">Update Album</button>
        <a href="{{ artist.get_absolute_url  }}" role="button" class="btn btn-secondary w-100">Cancel</a>
      </p>


</form>

{% endblock %}

core/templates/artist_create.html
{% extends 'base.html' %}

{% block content %}

      <form action="" method="post">
        {% for hidden_field in form.hidden_fields %}
          {{ hidden_field.errors }}
          {{ hidden_field }}
        {% endfor %}

        {% csrf_token %}

        {{ form.non_form_errors }}

        {% for field in form %}
          {{ field.errors }}
          {{ field.label_tag }} {{ field }}
        {% endfor %}

        <p class="pt-2">
            <button type="submit" class="btn btn-primary w-100 mb-2">Create Artist</button>
            <a href="{% url 'core:home' %}" role="button" class="btn btn-secondary w-100">Cancel</a>
        </p>
      </form>

{% endblock content %}

core/templates/artist_detail.html
{% extends 'base.html' %}

{% block Title %}{{ artist.name }}{% endblock %}

{% block content %}
{% if messages %}
{% for message in messages %}
<h4>{{ message }}</h4>
{% endfor %}
{% endif %}

<h3>{{ artist.name }} </h3>
    <!-- <div class="d-flex d-flex-inline"><span class="pe-2">Artist name:</span> <h5>{{ artist.name|title }}</h5></div> -->
    <hr>
        {% for collection in artist.collection_artist.all %}
        <div>Album: {{ collection.album }}</div>
        <div>Track: {{ collection.track }}</div>
        <hr>
        {% endfor %}
    <p>
        <a href="{% url 'core:album-edit' pk=artist.pk %}" role="button" class="btn btn-primary w-100 mb-2">Edit Artist Album</a>
        <a href="{% url 'core:artist_list' %}" role="button" class="btn btn-secondary w-100">All Albums</a>
    </p>

{% endblock %}

core/templates/artist_list.html
{% extends 'base.html' %}

{% block title %}Artists{% endblock %}

{% block content %}

<h4>All Artists </h4>

{% if artist_list %}
<ul class="list-group">
{% for artist in artist_list %}
<li class="list-group-item">
    <a class="text-reset" href="{{ artist.get_absolute_url }}">{{ artist.name }}</a>
</li>
{% endfor %}
</ul>
{% else %}
<p>Sorry! There are no artist registered. </p>
{% endif %}
<p class="pt-2">
    <a href="{% url 'core:home' %}" role="button" class="btn btn-secondary w-100">Cancel</a>
  </p>
{% endblock %}

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
    <main>
        <div class="container-fluid">
            <div class="d-flex align-items-center py-5">
                <div class="col-12 col-md-6 col-lg-4 mx-auto">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </main>
</body>
</html>

core/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}
{% block content %}
<a class='btn btn-secondary w-100 mb-2' role="button" href="{% url 'core:create_artist' %}">Create Account</a>
<a class='btn btn-secondary w-100 mb-2' role="button" href="{% url 'core:create_album' %}">Create Album</a>
<a class='btn btn-secondary w-100 mb-2' role="button" href="{% url 'core:artist_list' %}">All Artists</a>
<a class='btn btn-secondary w-100 mb-2' role="button" href="{% url 'core:album_list' %}">All Albums</a>

{% endblock %}